Update (changed to pure `sh`)

diff --git a/wpsotp b/wpsotp
--- a/wpsotp
+++ b/wpsotp
@@ -1,9 +1,9 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
-# Pure bash script to patch WPS Office Theme
+# Shell script to patch WPS Office Theme
 # Author: owl4ce
 # License: GPL-3.0
-# -------------------------------------------
+# --------------------------------
 # https://github.com/owl4ce/wpsotp
 
 # WPS Office Suite filename
@@ -12,61 +12,71 @@ PRESENTATION="wpp"
 SPREADSHEET="et"
 PDF="wpspdf"
 
+LC_ALL=C LANG=C R="\033[1;31m" G="\033[1;32m" M="\033[1;35m" W="\033[1;37m" NC="\033[0m"
+
+# Privilege detection
+if type -p "sudo" >/dev/null; then
+    PRIV="sudo"
+elif type -p "doas" >/dev/null; then
+    PRIV="doas"
+else
+    err "There is no ${M}sudo${NC} or ${M}doas${NC} installed."
+fi
+
 # Functions
-LC_ALL=C; LANG=C; R="\e[1;31m"; G="\e[1;32m"; M="\e[1;35m"; W="\e[1;37m"; NC="\e[0m"
-checkdep() { command -v "$1" > /dev/null 2>&1 || err "${M}$1${W} is not installed. Please install it first!${NC}"; }
+# - Check dependencies
+checkdep() { type -p "$1" >/dev/null || err "${M}$1${NC} is not installed. Please install it first!"; }
+# - Check GTK Theme
 checkgtk() {
     # GTK-2.0 rc file locations
     HOME_THEME_DIR="$HOME/.themes/$GTK_THEME_TARGET/gtk-2.0/gtkrc"
     GLOBAL_THEME_DIR="/usr/share/themes/$GTK_THEME_TARGET/gtk-2.0/gtkrc"
-    if [[ -f "$HOME_THEME_DIR" ]]; then
-        GTK_THEME="$HOME_THEME_DIR"; :
-    elif [[ -f "$GLOBAL_THEME_DIR" ]]; then
-        GTK_THEME="$GLOBAL_THEME_DIR"; :
+    if [ -f "$HOME_THEME_DIR" ]; then
+        GTK_THEME="$HOME_THEME_DIR"
+    elif [ -f "$GLOBAL_THEME_DIR" ]; then
+        GTK_THEME="$GLOBAL_THEME_DIR"
     else
-        err "${M}$GTK_THEME_TARGET${W} GTK Theme is not exists!"
+        err "${M}$GTK_THEME_TARGET${NC} GTK Theme is not exists!"
     fi
 }
-err() { echo -e "${R}==> Error:${W} $@${NC}"; exit 1; }
-msg() { echo -e "${G}==>${W} $@${NC}"; }
-msg_patch() { echo -e "${G}==>${M} $1${R} $2${NC}"; }
-msg_patching() { echo -e -n "${G}==>${W} $1${M} $2${W}$3${NC}"; }
-msg_patching_ok() { echo -e "${G} OK${NC}"; }
-msg_patching_fail() { echo -e "${R} FAIL${NC}"; }
+# - Output messages
+err() { printf "${R} > error: ${NC}$*\n"; exit 1; }
+msg() { printf "${G} > ${NC}$*\n"; }
+msg_patch() { printf "${G} > ${M}$1 ${NC}$2 ${R}(error)\n"; }
+msg_patching() { printf "${G} > ${NC}$1 ${M}$2 ${NC}$3"; }
+msg_patching_ok() { printf "${G} OK${NC}\n"; }
+msg_patching_fail() { printf "${R} FAIL${NC}\n"; }
 
-checkdep "$WRITER"; checkdep "$PRESENTATION"; checkdep "$SPREADSHEET"; checkdep "$PDF"; checkdep "sed"
-
-if [[ "$(command -v "sudo")" ]]; then
-    PRIV="sudo"
-elif [[ "$(command -v "doas")" ]]; then
-    PRIV="doas"
-else
-    err "There's no ${M}sudo${W} or ${M}doas${W} installed.${NC}"
-fi
+# Checks dependencies
+checkdep "$WRITER"
+checkdep "$PRESENTATION"
+checkdep "$SPREADSHEET"
+checkdep "$PDF"
+checkdep "sed"
 
 unpatch() {
-    if grep -E "\-style=gtk+|GTK2_RC_FILES" "$(command -v "$@")" &> /dev/null; then
-        $PRIV echo "" &> /dev/null; msg_patching "Unpatching" "$@" "..."
-        $PRIV sed -i 's\"-style=gtk+"\""\' "$(command -v "$@")" && \
-        [[ "$@" = "$PDF" ]] && $PRIV sed -i '/gOpt=".*"/d' "$(command -v "$@")" || : && \
-        $PRIV sed -i '/GTK2_RC_FILES/d' "$(command -v "$@")" && \
-        [[ "$@" = "$PDF" ]] && $PRIV sed -i 's\${gApp} ${gOpt} "\${gApp} "\' "$(command -v "$@")" || : && \
+    if grep -E "\-style=gtk+|GTK2_RC_FILES" "$(type -p "$*")" >/dev/null; then
+        $PRIV echo "" >/dev/null ; msg_patching "Unpatching" "$*" ".."
+        $PRIV sed -i 's\"-style=gtk+"\""\' "$(type -p "$*")" && \
+        [ "$*" = "$PDF" ] && $PRIV sed -i '/gOpt=".*"/d' "$(type -p "$*")" || : && \
+        $PRIV sed -i '/GTK2_RC_FILES/d' "$(type -p "$*")" && \
+        [ "$*" = "$PDF" ] && $PRIV sed -i 's\${gApp} ${gOpt} "\${gApp} "\' "$(type -p "$*")" || : && \
         msg_patching_ok || msg_patching_fail
     else
-        msg_patch "$@" "theme not patched!"
+        msg_patch "$*" "theme not patched!" ; !
     fi
 }
 
 patch() {
-    if ! grep -E "\-style=gtk+|GTK2_RC_FILES" "$(command -v "$@")" &> /dev/null; then
-        $PRIV echo "" &> /dev/null; msg_patching "Patching" "$@" "..."
-        $PRIV sed -i 's\gOpt=""\gOpt="-style=gtk+"\' "$(command -v "$@")" && \
-        [[ "$@" = "$PDF" ]] && $PRIV sed -i '/gBinPath=$(dirname "$0")/i gOpt="-style=gtk+"' "$(command -v "$@")" || : && \
-        $PRIV sed -i "/gOpt=\"-style=gtk+\"/a export GTK2_RC_FILES=$GTK_THEME" "$(command -v "$@")" && \
-        [[ "$@" = "$PDF" ]] && $PRIV sed -i 's\${gApp} "\${gApp} ${gOpt} "\' "$(command -v "$@")" || : && \
+    if ! grep -E "\-style=gtk+|GTK2_RC_FILES" "$(type -p "$*")" >/dev/null; then
+        $PRIV echo "" >/dev/null ; msg_patching "Patching" "$*" ".."
+        $PRIV sed -i 's\gOpt=""\gOpt="-style=gtk+"\' "$(type -p "$*")" && \
+        [ "$*" = "$PDF" ] && $PRIV sed -i '/gBinPath=$(dirname "$0")/i gOpt="-style=gtk+"' "$(type -p "$*")" || : && \
+        $PRIV sed -i "/gOpt=\"-style=gtk+\"/a export GTK2_RC_FILES=$GTK_THEME" "$(type -p "$*")" && \
+        [ "$*" = "$PDF" ] && $PRIV sed -i 's\${gApp} "\${gApp} ${gOpt} "\' "$(type -p "$*")" || : && \
         msg_patching_ok || msg_patching_fail
     else
-        msg_patch "$@" "theme already patched!"
+        msg_patch "$*" "theme already patched!" ; !
     fi
 }
 
@@ -76,12 +86,12 @@ case $1 in
         unpatch "$SPREADSHEET"
         unpatch "$PDF"
     ;;
-    -*) err "Unknown option $1"
+    -*) err "unknown option ($1)"
     ;;
     *)  msg "Enter GTK Theme to be applied!"
-        echo -n -e "${M}[${NC} Light Theme ${M}]\n${M}: $@${NC}"
-        read "GTK_THEME_TARGET" && checkgtk
-        msg_patching "Using" "$GTK_THEME_TARGET" " GTK Theme...\n"
+        printf " ${M}[${NC} Light Theme ${M}]\n ${M}: $*${NC}"
+        read GTK_THEME_TARGET ; checkgtk
+        msg_patching "Using" "$GTK_THEME_TARGET" "GTK Theme ..\n"
         patch "$WRITER"
         patch "$PRESENTATION"
         patch "$SPREADSHEET"
