Update POSIX-sh

diff --git a/wpsotp b/wpsotp
--- a/wpsotp
+++ b/wpsotp
@@ -15,6 +15,13 @@ PDF="wpspdf"
 LC_ALL=C LANG=C R="\033[1;31m" G="\033[1;32m" M="\033[1;35m" W="\033[1;37m" NC="\033[0m"
 
 # Functions
+# - Output messages
+err() { printf "${R} > error: ${NC}$*\n"; exit 1; }
+msg() { printf "${G} > ${NC}$*\n"; }
+msg_patch() { printf "${G} > ${M}$1 ${NC}$2 ${R}(error)\n"; }
+msg_patching() { printf "${G} > ${NC}$1 ${M}$2 ${NC}$3"; }
+msg_patching_ok() { printf "${G} OK${NC}\n"; }
+msg_patching_fail() { printf "${R} FAIL${NC}\n"; }
 # - Check dependencies
 checkdep() { type "$1" >/dev/null || err "${M}$1${NC} is not installed. Please install it first!"; }
 # - Check GTK Theme
@@ -30,13 +37,6 @@ checkgtk() {
         err "${M}$GTK_THEME_TARGET${NC} GTK Theme is not exists!"
     fi
 }
-# - Output messages
-err() { printf "${R} > error: ${NC}$*\n"; exit 1; }
-msg() { printf "${G} > ${NC}$*\n"; }
-msg_patch() { printf "${G} > ${M}$1 ${NC}$2 ${R}(error)\n"; }
-msg_patching() { printf "${G} > ${NC}$1 ${M}$2 ${NC}$3"; }
-msg_patching_ok() { printf "${G} OK${NC}\n"; }
-msg_patching_fail() { printf "${R} FAIL${NC}\n"; }
 
 # Privilege detection
 if type "sudo" >/dev/null; then
